name: Android CI & Release

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [created]   # 当你创建 GitHub Release 时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload APK (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download APK from build
        uses: actions/download-artifact@v4
        with:
          name: app-debug
          path: .

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
