name: Android CI & Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'   # 例如 v1.0.0 才会触发 Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      # Debug 构建（main 分支）
      - name: Build Debug APK
        if: github.ref == 'refs/heads/main'
        run: gradle assembleDebug --no-daemon

      - name: Upload Debug APK
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: iXapp-debug-apk
          path: app/build/outputs/apk/debug/*.apk

      # Release 构建（tag）
      - name: Build Release APK
        if: startsWith(github.ref, 'refs/tags/v')
        run: gradle assembleRelease --no-daemon

      - name: Upload Release APK to GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
